# install_startup.py
"""Register Parhi as a Windows startup application.

Usage:
    python install_startup.py            # Install auto-start
    python install_startup.py --remove   # Remove auto-start
    python install_startup.py --status   # Check if installed

Creates a shortcut in the Windows Startup folder so Parhi starts
automatically when the user logs in. Uses ``pythonw`` to run silently
without a console window.
"""
from __future__ import annotations

import argparse
import os
import sys
import winreg

if sys.stdout and hasattr(sys.stdout, "reconfigure"):
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
if sys.stderr and hasattr(sys.stderr, "reconfigure"):
    try:
        sys.stderr.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass


# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

_PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
_SERVICE_SCRIPT = os.path.join(_PROJECT_ROOT, "parhi_service.py")
_REGISTRY_KEY = r"Software\Microsoft\Windows\CurrentVersion\Run"
_REGISTRY_NAME = "ParhiAI"
_BAT_FILE = os.path.join(_PROJECT_ROOT, "parhi_service.bat")


# ---------------------------------------------------------------------------
# Startup folder method
# ---------------------------------------------------------------------------

def _get_startup_folder() -> str:
    """Get the Windows Startup folder path."""
    return os.path.join(
        os.environ.get("APPDATA", ""),
        "Microsoft", "Windows", "Start Menu", "Programs", "Startup",
    )


def _create_bat_launcher() -> str:
    """Create a .bat file that launches Parhi silently.

    Returns:
        Path to the .bat file.
    """
    # Find pythonw.exe
    python_dir = os.path.dirname(sys.executable)
    pythonw = os.path.join(python_dir, "pythonw.exe")
    if not os.path.exists(pythonw):
        pythonw = sys.executable  # Fallback to regular python

    bat_content = f"""@echo off
REM Parhi AI Background Service Launcher
REM Auto-generated by install_startup.py
cd /d "{_PROJECT_ROOT}"
start "" "{pythonw}" "{_SERVICE_SCRIPT}"
"""

    with open(_BAT_FILE, "w", encoding="utf-8") as f:
        f.write(bat_content)

    return _BAT_FILE


def _create_startup_shortcut() -> bool:
    """Create a shortcut in the Windows Startup folder.

    Returns:
        True if successful.
    """
    try:
        startup_folder = _get_startup_folder()
        if not os.path.exists(startup_folder):
            print(f"[!] Startup folder not found: {startup_folder}")
            return False

        shortcut_path = os.path.join(startup_folder, "ParhiAI.bat")

        # Create the bat launcher
        bat_path = _create_bat_launcher()

        # Copy bat to startup folder
        import shutil
        shutil.copy2(bat_path, shortcut_path)

        print(f"  [✓] Startup shortcut created: {shortcut_path}")
        return True

    except Exception as e:
        print(f"  [✗] Startup shortcut failed: {e}")
        return False


def _remove_startup_shortcut() -> bool:
    """Remove the Startup folder shortcut.

    Returns:
        True if removed.
    """
    startup_folder = _get_startup_folder()
    shortcut_path = os.path.join(startup_folder, "ParhiAI.bat")

    if os.path.exists(shortcut_path):
        os.remove(shortcut_path)
        print(f"  [✓] Startup shortcut removed: {shortcut_path}")
        return True
    else:
        print("  [–] No startup shortcut found.")
        return False


# ---------------------------------------------------------------------------
# Registry method (backup)
# ---------------------------------------------------------------------------

def _add_registry_entry() -> bool:
    """Add Parhi to Windows Registry Run key.

    Returns:
        True if successful.
    """
    try:
        bat_path = _create_bat_launcher()

        key = winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            _REGISTRY_KEY,
            0,
            winreg.KEY_SET_VALUE,
        )
        winreg.SetValueEx(key, _REGISTRY_NAME, 0, winreg.REG_SZ, bat_path)
        winreg.CloseKey(key)

        print(f"  [✓] Registry entry added: HKCU\\{_REGISTRY_KEY}\\{_REGISTRY_NAME}")
        return True

    except PermissionError:
        print("  [✗] Permission denied — try running as administrator.")
        return False
    except Exception as e:
        print(f"  [✗] Registry entry failed: {e}")
        return False


def _remove_registry_entry() -> bool:
    """Remove Parhi from Windows Registry Run key.

    Returns:
        True if removed.
    """
    try:
        key = winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            _REGISTRY_KEY,
            0,
            winreg.KEY_SET_VALUE,
        )
        try:
            winreg.DeleteValue(key, _REGISTRY_NAME)
            print(f"  [✓] Registry entry removed: {_REGISTRY_NAME}")
            removed = True
        except FileNotFoundError:
            print("  [–] No registry entry found.")
            removed = False
        winreg.CloseKey(key)
        return removed

    except Exception as e:
        print(f"  [✗] Registry removal failed: {e}")
        return False


# ---------------------------------------------------------------------------
# Status check
# ---------------------------------------------------------------------------

def check_status() -> None:
    """Check if Parhi is registered as a startup application."""
    print("\n  🔍 Parhi Startup Status")
    print("  " + "─" * 40)

    # Check startup folder
    startup_folder = _get_startup_folder()
    shortcut_path = os.path.join(startup_folder, "ParhiAI.bat")
    if os.path.exists(shortcut_path):
        print(f"  ✅ Startup folder: INSTALLED")
        print(f"     → {shortcut_path}")
    else:
        print(f"  ❌ Startup folder: NOT INSTALLED")

    # Check registry
    try:
        key = winreg.OpenKey(
            winreg.HKEY_CURRENT_USER,
            _REGISTRY_KEY,
            0,
            winreg.KEY_READ,
        )
        try:
            value, _ = winreg.QueryValueEx(key, _REGISTRY_NAME)
            print(f"  ✅ Registry: INSTALLED")
            print(f"     → {value}")
        except FileNotFoundError:
            print(f"  ❌ Registry: NOT INSTALLED")
        winreg.CloseKey(key)
    except Exception:
        print(f"  ❌ Registry: NOT INSTALLED")

    # Check bat file
    if os.path.exists(_BAT_FILE):
        print(f"  ✅ Launcher: EXISTS")
        print(f"     → {_BAT_FILE}")
    else:
        print(f"  ❌ Launcher: NOT CREATED")

    print()


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def install() -> None:
    """Install Parhi as a Windows startup application."""
    print()
    print("╔════════════════════════════════════════╗")
    print("║  🚀 Parhi Startup Installer            ║")
    print("╚════════════════════════════════════════╝")
    print()

    # Verify service script exists
    if not os.path.exists(_SERVICE_SCRIPT):
        print(f"  [✗] Service script not found: {_SERVICE_SCRIPT}")
        return

    # Method 1: Startup folder (user-level, no admin needed)
    success = _create_startup_shortcut()

    # Method 2: Registry (backup)
    if success:
        _add_registry_entry()

    if success:
        print()
        print("  ✅ Parhi will now start automatically when you log in!")
        print("  💡 Parhi will greet you and listen for your voice commands.")
        print()
        print("  To start Parhi now:")
        print(f"    pythonw {_SERVICE_SCRIPT}")
        print()
        print("  To remove auto-start:")
        print(f"    python {__file__} --remove")
        print()
    else:
        print("\n  ❌ Installation failed. Please try running as administrator.\n")


def uninstall() -> None:
    """Remove Parhi from Windows startup."""
    print()
    print("  🗑️ Removing Parhi from startup...")
    _remove_startup_shortcut()
    _remove_registry_entry()

    # Clean up bat file
    if os.path.exists(_BAT_FILE):
        os.remove(_BAT_FILE)
        print(f"  [✓] Launcher removed: {_BAT_FILE}")

    print("  ✅ Parhi will no longer start automatically.\n")


def main() -> None:
    """CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Install or remove Parhi as a Windows startup application."
    )
    parser.add_argument(
        "--remove", action="store_true",
        help="Remove Parhi from startup.",
    )
    parser.add_argument(
        "--status", action="store_true",
        help="Check if Parhi is registered as a startup app.",
    )
    args = parser.parse_args()

    if args.status:
        check_status()
    elif args.remove:
        uninstall()
    else:
        install()


if __name__ == "__main__":
    main()
